export const projects = [
  {
    id: 1,
    title: "SimJob",
    year:2025,
    tagline: "AI-powered mock interview platform for real-time interview preparation.",
    category: "AI/ML",
    duration: "4 months",
    role: "Full Stack Developer",
    status: "Live",
    description:
      "SimJob is an AI-powered mock interview platform that replicates real interview experiences using speech recognition, text-to-speech, and AI-driven feedback. It enables users to practice company-specific interviews and online assessments in a realistic environment.",
    challenge:
      "Creating a low-latency, real-time interaction system for voice-based interviews while maintaining accuracy and natural flow was challenging. Managing AI responses, TTS/STT synchronization, and scalable server connections demanded robust architecture.",
    solution:
      "Implemented WebSocket-based real-time communication, integrated Gemini API for AI responses, and used Coqui TTS with Whisper for speech synthesis and recognition. Optimized backend for faster response times and consistent interview flow.",
    image: "/images/simjob.webp",
    category: "AI/ML",
    tech: ["React", "Node.js", "WebSockets", "Gemini", "TTS", "STT"],
    technologies: [
      { name: "React", category: "Frontend" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "Node.js", category: "Backend" },
      { name: "Express.js", category: "Backend" },
      { name: "BullMQ", category: "Backend" },
      { name: "MongoDB", category: "Database" },
      { name: "Redis", category: "Database" },
      { name: "Gemini", category: "LLM" },
      { name: "WebSockets", category: "Real-time" },
      { name: "Google cloud TTS", category: "LLM" },
      { name: "Google cloud STT", category: "LLM" },
    ],
    features: [
      "Real-time AI-powered interviews",
      "Speech-to-text and text-to-speech integration",
      "Company-specific mock interview generation",
      "Low-latency WebSocket communication",
      "AI-driven feedback and analysis",
    ],
    links: {
      github: "https://github.com/sahilwarkhade/simjob_client",
      live: "https://simjob.space",
      case_study: "#",
    },
    images: [
      "/images/simjob.webp",
      "/images/simjob.webp",
      "/images/simjob.webp",
    ],
    metrics: [
      { label: "Response Latency", value: "< 500ms" },
      { label: "Accuracy", value: "95%" },
      { label: "Active Users", value: "500+" },
      { label: "Feedback Generated", value: "2000+" },
    ],
    featured: true,
  },
  {
    id: 2,
    title: "LearnNotion",
    year:2024,
    tagline: "Next-gen Learning Management System for course creation and delivery.",
    category: "Web App",
    duration: "3 months",
    role: "Full Stack Developer",
    status: "Live",
    description:
      "LearnNotion is a full-featured MERN-based LMS that allows educators to create, manage, and monetize courses while enabling learners to consume, rate, and review content in a seamless environment.",
    challenge:
      "Designing a scalable platform capable of managing large amounts of media content and handling secure payments without compromising on speed or user experience.",
    solution:
      "Used Cloudinary for efficient media storage and NodeMailer for communication. Integrated secure payment APIs and Redux Toolkit for state management, ensuring smooth and reliable performance.",
    image: "/images/learnnotion.webp",
    tech: ["React", "Node.js", "MongoDB", "Cloudinary", "Redux Toolkit"],
    technologies: [
      { name: "React", category: "Frontend" },
      { name: "Redux", category: "Frontend" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "Node.js", category: "Backend" },
      { name: "Express.js", category: "Backend" },
      { name: "MongoDB", category: "Database" },
      { name: "Cloudinary", category: "Media" },
      { name: "NodeMailer", category: "Communication" },
      { name: "Razorpay", category: "Payment Integration" },
    ],
    features: [
      "Course creation and management",
      "Media upload and content streaming",
      "Payment integration and receipts",
      "Role-based access control",
      "Email notifications for users",
    ],
    links: {
      github: "https://github.com/sahilwarkhade/LearnNotion_Client",
      live: "https://learnnotion.vercel.app",
      case_study: "#",
    },
    images: [
      "/images/learnnotion.webp",
      "/images/learnnotion.webp",
      "/images/learnnotion.webp",
    ],
    metrics: [
      { label: "Courses Hosted", value: "100+" },
      { label: "Users", value: "1K+" },
      { label: "Response Time", value: "< 1s" },
      { label: "Uptime", value: "99.9%" },
    ],
    featured: true,
  },
  {
    id: 3,
    title: "Epicentra",
    year:2024,
    tagline: "Community blogging platform for creators and readers.",
    category: "Web App",
    duration: "3 months",
    role: "Full Stack Developer",
    status: "Live",
    description:
      "Epicentra is a community-driven blogging platform that enables users to read, write, and engage with diverse blogs. Built using Editor.js for a rich content experience and Cloudinary for seamless media handling.",
    challenge:
      "Creating a flexible editor with multimedia support while maintaining high performance and responsive UI for large posts.",
    solution:
      "Integrated Editor.js for structured content creation and Cloudinary for efficient media handling. Used MongoDB for scalable data storage and Express for fast API communication.",
    image: "/images/epicentra.webp",
    tech: ["React", "Node.js", "Express", "MongoDB", "Editor.js"],
    technologies: [
      { name: "React", category: "Frontend" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "React Context", category: "Frontend" },
      { name: "Node.js", category: "Backend" },
      { name: "Express", category: "Backend" },
      { name: "MongoDB", category: "Database" },
      { name: "Editor.js", category: "Rich Text" },
      { name: "Cloudinary", category: "Media" },
    ],
    features: [
      "Rich text editor for blogs",
      "Image and video uploads",
      "Like and comment system",
      "User profiles and dashboards",
      "SEO-friendly blog URLs",
    ],
    links: {
      github: "https://github.com/sahilwarkhade/Epicentra-Frontend",
      live: "https://epicentra.vercel.app",
      case_study: "#",
    },
    images: [
      "/images/epicentra.webp",
      "/images/epicentra.webp",
      "/images/epicentra.webp",
    ],
    metrics: [
      { label: "Posts Published", value: "500+" },
      { label: "Active Users", value: "300+" },
      { label: "Load Time", value: "< 2s" },
      { label: "Uptime", value: "99.9%" },
    ],
    featured: false,
  },
  {
    id: 4,
    title: "CompileCode",
    tagline: "Browser-based real-time code execution platform.",
    category: "Tool",
    duration: "3 months",
    role: "Full Stack Developer",
    status: "Live",
    description:
      "CompileCode is an online coding platform that lets users write, run, and share code in multiple languages, directly from the browser. It provides real-time execution results in a secure sandboxed environment.",
    challenge:
      "Building a safe and scalable sandbox environment to execute untrusted user code while ensuring fast performance and isolation.",
    solution:
      "Used Docker containers for isolated code execution and WebSockets for real-time interaction. Optimized backend task queues to handle multiple concurrent executions efficiently.",
    image: "/images/compilecode.webp",
    tech: ["React", "Node.js", "Express", "Docker", "WebSockets"],
    technologies: [
      { name: "React", category: "Frontend" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "Node.js", category: "Backend" },
      { name: "Redis", category: "Backend" },
      { name: "Express", category: "Framework" },
      { name: "Docker", category: "DevOps" },
      { name: "WebSockets", category: "Real-time" },
    ],
    features: [
      "Multi-language code execution",
      "Real-time result display",
      "Secure containerized environment",
      "Collaborative code sharing",
      "Syntax highlighting editor",
    ],
    links: {
      github: "https://github.com/sahilwarkhade/Compilecode_Client",
      live: "https://compilecode.vercel.app",
      case_study: "#",
    },
    images: [
      "/images/compilecode.webp",
      "/images/compilecode.webp",
      "/images/compilecode.webp",
    ],
    metrics: [
      { label: "Supported Languages", value: "10+" },
      { label: "Execution Time", value: "< 1s" },
      { label: "Concurrent Users", value: "100+" },
    ],
    featured: false,
  },
  {
    id: 5,
    title: "LinkSpin",
    tagline: "URL shortener and analytics dashboard service.",
    category: "Web App",
    duration: "2 months",
    role: "Full Stack Developer",
    status: "Live",
    description:
      "LinkSpin is a URL shortener service that provides analytics like click tracking, location insights, and referrer data. Built with a simple yet powerful dashboard for managing and analyzing links.",
    challenge:
      "Designing an analytics engine to track thousands of link requests efficiently without compromising on speed.",
    solution:
      "Implemented efficient MongoDB indexing, integrated Chart.js for data visualization, and optimized backend routes for handling high request loads.",
    image: "/images/linkspin.webp",
    tech: ["React", "Node.js", "Express", "MongoDB", "Chart.js"],
    technologies: [
      { name: "React", category: "Frontend" },
      { name: "Chart.js", category: "Frontend" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "Node.js", category: "Backend" },
      { name: "Express", category: "Framework" },
      { name: "MongoDB", category: "Database" },
    ],
    features: [
      "Shorten and manage URLs",
      "Analytics dashboard with charts",
      "Click tracking and insights",
      "Link expiration and custom slugs",
      "Responsive modern UI",
    ],
    links: {
      github: "https://github.com/sahilwarkhade/shortURL-service",
      live: "https://linkspin.vercel.app",
      case_study: "#",
    },
    images: [
      "/images/linkspin.webp",
      "/images/linkspin.webp",
      "/images/linkspin.webp",
    ],
    metrics: [
      { label: "Links Shortened", value: "5K+" },
      { label: "Avg Response", value: "< 300ms" },
      { label: "Uptime", value: "99.9%" },
    ],
    featured: false,
  },
  {
  id: 6,
  title: "RagStudio",
  year:"2025",
  tagline: "AI-powered document intelligence and conversational RAG platform.",
  category: "AI/ML",
  duration: "15 Days",
  role: "Full Stack Developer",
  status: "Live",
  description:
    "RagStudio is an AI-powered document intelligence platform that enables users to upload PDFs and interact with their content through a conversational interface using Retrieval-Augmented Generation (RAG). The system processes documents asynchronously, stores embeddings in a vector database, and delivers context-aware, low-latency responses.",
  challenge:
    "Designing a scalable and non-blocking document ingestion pipeline capable of handling large PDFs, real-time conversations, and AI-driven retrieval without impacting API performance.",
  solution:
    "Implemented an asynchronous worker-based architecture using BullMQ and Redis to offload PDF parsing, chunking, and embedding generation, combined with Qdrant vector search and WebSocket-based real-time chat for low-latency, scalable interactions.",
  image: "/images/ragstudio.webp",
  tech: [
    "Node.js",
    "Express",
    "MongoDB",
    "Redis",
    "BullMQ",
    "LangChain",
    "Qdrant",
    "WebSockets",
    "NGINX",
    "GCP",
  ],
  technologies: [
    { name: "Node.js", category: "Backend" },
    { name: "Express", category: "Framework" },
    { name: "MongoDB", category: "Database" },
    { name: "Redis", category: "Cache / Queue" },
    { name: "BullMQ", category: "Background Jobs" },
    { name: "LangChain", category: "AI / NLP" },
    { name: "Qdrant", category: "Vector Database" },
    { name: "WebSockets", category: "Realtime" },
    { name: "NGINX", category: "Infrastructure" },
    { name: "GCP VM", category: "Cloud" },
  ],
  features: [
    "PDF upload and intelligent document ingestion",
    "Asynchronous processing with background workers",
    "Vector-based semantic search using Qdrant",
    "Conversational AI powered by RAG",
    "Real-time chat using WebSockets",
    "Secure authentication and user-specific document isolation",
    "Document lifecycle management (upload, process, delete)",
  ],
  links: {
    github: "https://github.com/sahilwarkhade/rag-studio-backend",
    live: "https://rag.sahilwarkhade.com",
    case_study: "#",
  },
  images: [
    "/images/ragstudio.webp",
    "/images/ragstudio.webp",
    "/images/ragstudio.webp",
  ],
  metrics: [
    { label: "Documents Processed", value: "1K+" },
    { label: "Avg Query Latency", value: "< 500ms" },
    { label: "Uptime", value: "99.9%" },
  ],
  featured: true,
}
];
